/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemroom;

import static java.awt.image.ImageObserver.WIDTH;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class EditCustomer extends javax.swing.JFrame implements CustomersList, HistoryList, TableModel{

    private Customers ECustomer;
    private String oldID;
    private DateFormat DateFormat = new SimpleDateFormat("d/M/y");
    private String newID;
    private String newFName;
    private String newLName;
    private String newBirthday;
    private String newSex;
    private String newTel;
    private String newAd;
    public EditCustomer(Customers Customer) {
        SimpleDateFormat DateFormat = new SimpleDateFormat("d/M/y");
        initComponents();
        this.ECustomer = Customer;
        this.oldID = Customer.ID;
        editIDCard.setText(Customer.ID);
        editFName.setText(Customer.FName);
        editLName.setText(Customer.LName);
        //editBirthday.setDate(DateFormat.parse(Customer.Birthday));
        editSex.setSelectedItem(Customer.Sex);
        editTel.setText(Customer.Tel);
        editAd.setText(Customer.Ad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CInfoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editIDCard = new javax.swing.JTextField();
        FName = new javax.swing.JLabel();
        editFName = new javax.swing.JTextField();
        LName = new javax.swing.JLabel();
        editLName = new javax.swing.JTextField();
        BirthdayLable = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        editSex = new javax.swing.JComboBox<>();
        tel = new javax.swing.JLabel();
        editTel = new javax.swing.JTextField();
        ad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editAd = new javax.swing.JTextArea();
        editBirthday = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        alert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Customer");

        CInfoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CInfoPanel.setFocusable(false);

        jLabel1.setText("ID card : ");

        FName.setText("First Name : ");

        LName.setText("Last Name : ");

        BirthdayLable.setText("Birthday : ");

        sex.setText("Gender : ");

        editSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        tel.setText("Tel : ");

        ad.setText("Address : ");

        editAd.setColumns(20);
        editAd.setRows(5);
        jScrollPane1.setViewportView(editAd);

        editBirthday.setDateFormatString("d/M/y");

        javax.swing.GroupLayout CInfoPanelLayout = new javax.swing.GroupLayout(CInfoPanel);
        CInfoPanel.setLayout(CInfoPanelLayout);
        CInfoPanelLayout.setHorizontalGroup(
            CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CInfoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BirthdayLable)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(tel)
                        .addComponent(FName))
                    .addGroup(CInfoPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(ad)))
                .addGroup(CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editIDCard, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editTel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CInfoPanelLayout.createSequentialGroup()
                        .addGroup(CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editFName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CInfoPanelLayout.createSequentialGroup()
                                .addComponent(sex)
                                .addGap(1, 1, 1)
                                .addComponent(editSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CInfoPanelLayout.createSequentialGroup()
                                .addComponent(LName)
                                .addGap(0, 0, 0)
                                .addComponent(editLName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        CInfoPanelLayout.setVerticalGroup(
            CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CInfoPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(editIDCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FName)
                    .addComponent(editFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LName)
                    .addComponent(editLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BirthdayLable, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sex)
                        .addComponent(editSex, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel)
                    .addComponent(editTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ad))
                .addGap(18, 18, 18))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Edit Customer");

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        alert.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(CInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alert, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(CInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Do you want edit customer?", "Edit Confirm", WIDTH)==0){
            newID = editIDCard.getText();
            newFName = editFName.getText();
            newLName = editLName.getText();
            newSex = editSex.getSelectedItem().toString();
            newTel = editTel.getText();
            newAd = editAd.getText();
            int found = 0;
            for(Customers c :Customer){
                if(c.ID.equals(newID)){
                    found += 1;
                    break;
                }
            }
            if(found==1){
                if(checkText()){
                    newBirthday = DateFormat.format(editBirthday.getDate());
                    ECustomer.Edit(newID, newFName, newLName, newBirthday, newSex, newTel, newAd);
                    int count = THistory.getRowCount();
                    for(int i=0;i<count;i++){
                        try{
                            if(THistory.getValueAt(i,0).equals(oldID)){
                                THistory.setValueAt(newID, i, 1);
                            }
                        }catch(Exception e){}
                        try{
                            if(TCustomers.getValueAt(i,0).equals(oldID)){
                                TCustomers.setValueAt(newID, i, 0);
                                TCustomers.setValueAt(newFName, i,1);
                                TCustomers.setValueAt(newLName, i,2);
                                TCustomers.setValueAt(newBirthday, i,3);
                                TCustomers.setValueAt(newSex, i,4);
                                TCustomers.setValueAt(newTel, i,5);
                                TCustomers.setValueAt(newAd, i,6);
                            }
                        }catch(Exception e){}
                    }
                    for(History h : History){
                        if(h.ID.equals(oldID)){
                            h.ID = newID;
                        }
                    }
                    setVisible(false);
                }else{
                    alert.setText("Please complete the following information!!");
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Can not edit to "+newID, "Edit "+oldID, HEIGHT);
            }
        }
    }//GEN-LAST:event_editActionPerformed
    
    private boolean checkText(){
        System.out.print(newBirthday);
        if(!newID.isEmpty()&&!newFName.isEmpty()&&!newLName.isEmpty()&&!newTel.isEmpty()&&!newAd.isEmpty()&&editBirthday.getDate()!=null){
            return true;
        }
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCustomer(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BirthdayLable;
    private javax.swing.JPanel CInfoPanel;
    private javax.swing.JLabel FName;
    private javax.swing.JLabel LName;
    private javax.swing.JLabel ad;
    private javax.swing.JLabel alert;
    private javax.swing.JButton edit;
    private javax.swing.JTextArea editAd;
    private com.toedter.calendar.JDateChooser editBirthday;
    private javax.swing.JTextField editFName;
    private javax.swing.JTextField editIDCard;
    private javax.swing.JTextField editLName;
    private javax.swing.JComboBox<String> editSex;
    private javax.swing.JTextField editTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel tel;
    // End of variables declaration//GEN-END:variables
}
